apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd.name" . }}-externalsecrets
  namespace: {{ .Release.Namespace }}
  labels:
    jamf.com/application: buildsvc
    jamf.com/environment: {{ .Values.cluster.environment }}
    jamf.com/cluster-type: eks
    jamf.com/region: eu-central-1
    {{- include "argocd.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cluster.externalSecretIAM }}
