apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jamf/argocd-infrastructure.git
    targetRevision: JSC-59106-init
    path: ./sbox
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
#  syncPolicy:
#    automated: {}
