apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'argocd-infrastructure'
  labels:
    team: delta
    app: argocd
    cluster-type: eks
    cluster: euc1-delta-sbox240423
    environment: sbox
    region: eu-central-1
spec:
  project: default
  source:
    repoURL: https://github.com/jamf/argocd-infrastructure.git
    targetRevision: JSC-58687-argocd-upgrade
    path: 'charts/argocd'
    helm:
      valueFiles:
      - values.yaml
      - values-sbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-infrastructure
