apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'argocd-sbox'
  labels:
    team: delta
    app: argocd
    cluster-type: k8s
    location: euc1-delta-sbox240423
    environment: sbox
spec:
  project: default
  source:
    repoURL: https://github.com/jamf/argocd-infrastructure.git
    targetRevision: JSC-59106-init
    path: 'charts/argocd'
    helm:
      valueFiles:
      - values.yaml
      - values-sbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
