apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'argocd'
  labels:
    team: delta
    app: argocd
    cluster-type: k8s
    location: euc1-buildsvc-prod240515
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/jamf/argocd-infrastructure.git
    targetRevision: HEAD
    path: 'charts/argocd'
    helm:
      valueFiles:
      - values.yaml
      - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
