cluster:
  name: "euc1-delta-sbox240423"
  environment: "sbox"
  region: "eu-central-1"
  externalSecretIAM: "arn:aws:iam::082372472775:role/argocd-infrastructure-secret-sbox"

argo-cd:
  controller:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    metrics:
      enabled: false

  externalRedis:
    host: argocd-infra-sbox-eu-central-1-redis-001.0sjexd.0001.euc1.cache.amazonaws.com

  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    metrics:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - "argocd-infrastructure.sbox.jamf.build"

  repoServer:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
    metrics:
      enabled: false

  applicationSet:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    metrics:
      enabled: false

  configs:
    cm:
      url: https://argocd-infrastructure.sbox.jamf.build
      admin.enabled: true
