nameOverride: ""

cluster:
  server: https://kubernetes.default.svc
  name: ""
  environment: ""
  region: ""
  owner: "delta"
  externalSecretIAM: ""

ingressExternal:
  enabled: false
  host: ""
  annotations: []

argo-cd:
  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "argocd"
    config:
      application.resourceTrackingMethod: annotation

  redis:
    enabled: false

  redis-ha:
    enabled: false

  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "argocd"
    extraContainers:
      - name: argocd-cmp
        command: [/var/run/argocd/argocd-cmp-server]
        args: ["--logformat=json"]
        image: 359585083818.dkr.ecr.us-east-1.amazonaws.com/jamf/ga/argocd/cmp:78506f6
        env:
          - name: HELM_CACHE_HOME
            value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /helm-working-dir
            name: helm-working-dir
        resources:
          limits:
            memory: 1.5Gi
          requests:
            cpu: 800m
            memory: 1Gi

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "argocd"

  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "argocd"

  notifications:
    enabled: false

  configs:
    params:
      "applicationsetcontroller.policy": "create-update"
    cm:
      admin.enabled: true
      accounts.applications-syncer: apiKey
      accounts.terraform: apiKey

    rbac:
      policy.csv: |
        p, terraform, clusters, *, *, allow
        p, role:applications-sync, applications, sync, *, allow
        g, applications-syncer, role:admin
        g, Wandera - Delta Team, role:admin
      scopes: '[email,groups]'
