cluster:
  name: "euc1-delta-sbox240423"
  environment: "sbox"

argo-cd:
  controller:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    metrics:
      enabled: false

  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    metrics:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - "argocd-infrastructure.sbox.jamf.build"

  repoServer:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
    metrics:
      enabled: false

  applicationSet:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    metrics:
      enabled: false

  configs:
    cm:
      url: https://argocd-infrastructure.sbox.jamf.build
      admin.enabled: true
