name: 'Manual - plan or destroy sbox'
run-name: ${{ github.actor }} running Terragrunt ${{ inputs.action }} on sbox 🚀

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Terragrunt action to perform against sbox environment'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - destroy

concurrency:
  group: ${{ github.workflow }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all 
 
jobs:
  discover-environments:
    name: Discover Environments
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    outputs:
      sbox-environments: ${{ steps.list-sbox-environments.outputs.environments }}
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v4
    - name: Output sbox environments
      uses: jamf/github-actions-terragrunt/discover-environments@v1.2.1
      id: list-sbox-environments
      with:
        environment: sbox

  plan-sbox:
    if: ${{ github.event.inputs.action == 'plan' && needs.discover-environments.outputs.sbox-environments != 'empty' }}
    name: Plan sbox
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    needs: discover-environments
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.sbox-environments) }}
      fail-fast: false
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Plan sbox'
      uses: jamf/github-actions-terragrunt/terragrunt-action@v1.2.1
      with:
        environment: ${{ matrix.environments }}
        action: plan
        gh_app_secret: ${{ secrets.GH_APP_INFRA_MODULES_PRIVATE_KEY }}
        gh_app_id: ${{ secrets.GH_APP_INFRA_MODULES_ID }}
        account_id: "082372472775"

  destroy-sbox:
    if: ${{ github.event.inputs.action == 'destroy' && needs.discover-environments.outputs.sbox-environments != 'empty' }}
    name: Destroy sbox
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    needs: discover-environments
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.sbox-environments) }}
      fail-fast: false
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Destroy sbox'
      uses: jamf/github-actions-terragrunt/terragrunt-action@v1.2.1
      with:
        environment: ${{ matrix.environments }}
        action: destroy
        gh_app_secret: ${{ secrets.GH_APP_INFRA_MODULES_PRIVATE_KEY }}
        gh_app_id: ${{ secrets.GH_APP_INFRA_MODULES_ID }}
        account_id: "082372472775"
