name: 'Terragrunt plan'
run-name: ${{ github.actor }} planning to deploy 🚀

on:
  pull_request:
    paths:
    - 'infrastructure/**'

concurrency:
  group: ${{ github.workflow }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


permissions: write-all # This is required for actions/checkout

jobs:
  discover-environments:
    name: Discover environments
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    outputs:
      sbox-environments: ${{ steps.list-sbox-environments.outputs.environments }}
      staging-environments: ${{ steps.list-staging-environments.outputs.environments }}
      production-environments: ${{ steps.list-production-environments.outputs.environments }}
    steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v4
    - name: Output sbox environments
      uses: jamf/github-actions-terragrunt/discover-environments@v1.0.0
      id: list-sbox-environments
      with:
        environment: sbox
    - name: Output staging environments
      uses: jamf/github-actions-terragrunt/discover-environments@v1.0.0
      id: list-staging-environments
      with:
        environment: staging
    - name: Output production environments
      uses: jamf/github-actions-terragrunt/discover-environments@v1.0.0
      id: list-production-environments
      with:
        environment: production

  plan-sbox:
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    needs: discover-environments
    if: ${{ needs.discover-environments.outputs.sbox-environments != 'empty' }}
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.sbox-environments) }}
      fail-fast: false
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: plan
      uses: jamf/github-actions-terragrunt/terragrunt-action@v1.2.1
      with:
        environment: ${{ matrix.environments }}
        action: plan
        gh_app_secret: ${{ secrets.GH_APP_INFRA_MODULES_PRIVATE_KEY }}
        gh_app_id: ${{ secrets.GH_APP_INFRA_MODULES_ID }}
        account_id: "082372472775"

  plan-staging:
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    needs: discover-environments
    if: ${{ needs.discover-environments.outputs.staging-environments != 'empty' }}
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.staging-environments) }}
      fail-fast: false
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: plan
      uses: jamf/github-actions-terragrunt/terragrunt-action@v1.2.1
      with:
        environment: ${{ matrix.environments }}
        action: plan
        gh_app_secret: ${{ secrets.GH_APP_INFRA_MODULES_PRIVATE_KEY }}
        gh_app_id: ${{ secrets.GH_APP_INFRA_MODULES_ID }}
        account_id: "851725295329"

  plan-production:
    runs-on: [ "self-hosted", "jamf-ubuntu-latest" ]
    needs: discover-environments
    if: ${{ needs.discover-environments.outputs.production-environments != 'empty' }}
    strategy:
      matrix: ${{ fromJson(needs.discover-environments.outputs.production-environments) }}
      fail-fast: false
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: plan
      uses: jamf/github-actions-terragrunt/terragrunt-action@v1.2.1
      with:
        environment: ${{ matrix.environments }}
        action: plan
        gh_app_secret: ${{ secrets.GH_APP_INFRA_MODULES_PRIVATE_KEY }}
        gh_app_id: ${{ secrets.GH_APP_INFRA_MODULES_ID }}
        account_id: "992382493208"
